attr_noise_scale: 300
adj_noise_scale: 0

alpha: 0.01
pre_n_samples: 10
n_samples: 1000

certify: False

classifier: 'GraphSAGE'
classifier_path: 'checkpoint_classifier/save_model/GIN/GIN_IMDB-BINARY_sum_0_5_h64.pt'
