attr_noise_scale: 0
adj_noise_scale: 0

alpha: 0.01
pre_n_samples: 1
n_samples: 1

certify: False

classifier: 'gin'
classifier_nlayers: 2
classifier_path: 'checkpoint_classifier/save_model/GIN/GIN_MUTAG_avg_0_2_h64.pt'
